#!/bin/bash

rm -rf bench* 

for i in `seq 2 5 5`; do
   for fair in 1 2 5 10 100; do
      for episode in 15 30 50; do
         for epoch in 10 50 100 200; do
             for hidden in 10 50 100 200; do
                (time java -jar ../RERL-default.jar -mode=infinite -fair=$fair -episode=$episode -epoch=$epoch -hidden=$hidden -good=1 -bad=-1 dp$i.bip dp$i-$fair-$episode-$epoch-$hidden.cpp dp$i.bad) &>> bench-$i-$fair-$episode-$epoch-$hidden
   g++ -o run-$i-$fair-$episode-$epoch-$hidden dp$i-$fair-$episode-$epoch-$hidden.cpp -std=c++11 
   echo -e "dining-"$i"-fair: "$fair" - episode: "$episode" - epoch: "$epoch" - hidden: "$hidden": \c" >> bench-current
   ./run-$i-$fair-$episode-$epoch-$hidden | wc -l >>  bench-current
             done
         done
      done
   done
   (time java -jar ../RERL-default.jar -mode=standard  dp$i.bip dp$i-standard.cpp dp$i.bad) &>> bench-standard
   g++ -o run-$i-standard dp$i-standard.cpp -std=c++11
   echo -e "dining-"$i"-standard: \c" >> bench-current
   ./run-$i-standard | wc -l >>  bench-current
done



