#!/bin/bash

build_infinite() {
  gridSize=$((3*$4))
  rm -rf tmp
  java -jar ../RERL.jar -mode=infinite -episode=$1 -epoch=$2  -hidden=$3  robots$4_$5.bip robots$4_$5.cpp robots$4_$5.bad > /dev/null
  g++ -o run robots$4_$5.cpp -std=c++11
  ./run >> tmp

  counts=`cat tmp | awk -F ":-->" '{print $2 $3}' | awk '$1 >= '"$gridSize"' || $2 >= '"$gridSize"'' | wc -l`
  if test $counts -eq 0; then
    echo Good >> bench
  else
    echo Bad >> bench
  fi
}


for i in `seq 25 25 25`; do
   rm -rf bench
   for j in `seq 1 1 40`; do
      echo $j
      build_infinite 20 20 200 $i 2
   done
   echo "robots " $i "__5"
   echo "Good " $(cat bench | grep Good | wc -l) "out of" $(cat bench | wc -l)
done


